server:
  port: 2021
  error:
    include-stacktrace: never
    
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        '[format_sql]': true

app:
  secret: pratik

